# Generated by Django 5.2.4 on 2025-07-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='Is it Done',
            new_name='isdone',
        ),
    ]
